INSERT INTO user (name)
VALUES ("DE 05 Mark och Betong"),
("DE 15 Finplanering Mark"),
("DE 01 Prefabstomme"),
("DE 06 Fönster"),
("DE 07 Glaspartier metall"),
("DE 12 Glaspartier Trä"),
("DE 14 Mellanväggar"),
("DE 16 Golvavjämning"),
("DE 17 Natursten"),
("DE 18 Plattsättning"),
("DE 19  Storköksutrustning"),
("DE 20 Möbler"),
("DE 23 Bygg"),
("DE 24 Undertak"),
("DE 25 Golvbeläggning"),
("DE 27 Solavskärmning pl.2"),
("DE 28 Solavskärmning pl.3-6"),
("DE 29 Brand- och ljudtätningar"),
("DE 30 Målning"),
("DE 33 Skyltning"),
("DE 38  Kittentreprenad"),
("DE 40 Centraltrappa"),
("DE 41 Takarbeten"),
("DE 42 Smide"),
("DE 43 Plåt"),
("DE 44 Receptions- och serveringsdisk"),
("DE 45 Askräcken"),
("DE 46 Lås och beslag"),
("DE 48 Massagolv"),
("DE 09 Ventilation"),
("DE 37 Ventilationsaggregat"),
("DE 08 El"),
("DE 26 Solpaneler"),
("DE 21 AV-utrustning"),
("DE 03 Hiss"),
("DE 13 Styr och Övervakning"),
("DE 10 Rör"),
("DE 35 Kökskyla och hg kylrum"),
("DE 39 Kylmaskiner mm innan bjk över plan 1"),
("DE 11 Sprinkler")

