branch-defaults:
  byggstyrning:
    environment: node-express-env
    group_suffix: null
environment-defaults:
  node-express-env:
    branch: null
    repository: null
global:
  application_name: react
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
