branch-defaults:
  byggstyrning:
    environment: node-express-env
    group_suffix: null
global:
  application_name: react
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  profile: null
  repository: null
  sc: git
