import $ from "jquery";
import React from "react";
import CSSModules from "react-css-modules";
import { connect } from 'react-redux';
import styles from "./ConstructionForm.less";
import MaterialSelection from "./MaterialSelection.jsx";

class ConstructionForm extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			name: this.props.constructionName ? this.props.constructionName : '',
			unit: '',
			materialComposition: [],
			constructionParts: this.props.constructionParts ? this.props.constructionParts : 0,
			constructionCreation: this.props.constructionCreation ? this.props.constructionCreation : false
		};
	}

	handleNameUnitChange(e) {
		this.setState({
			[e.target.name]: e.target.value
		});
	}

	createConstructionPartClicked(e, constructionType) {
		e.preventDefault();
		this.createConstructionPart(constructionType);
	}

	createConstructionPart(constructionType) {
		const constructionParts = constructionType == 'prefab' ? 1 : 0;
		this.setState({
			name: '',
			unit: '',
			materialComposition: [],
			constructionParts,
			constructionCreation: constructionType
		});
	}

	addConstructionPart(e) {
		e.preventDefault();
		this.setState({
			constructionParts: this.state.constructionParts + 1
		});
	}

	removeConstructionPart(e) {
		e.preventDefault();
		this.setState({
			constructionParts: this.state.constructionParts - 1
		});
		//FIXME: This also needs to go through the state and remove the unwanted material
	}

	handleMaterialChange(material) {
		const {materialComposition} = this.state;
		if (material.material == 'createNew') {
			this.createConstructionPart('standard');
			return;
		}
		let materialArray = materialComposition;
		materialArray[material.materialIndex] = material;
		materialArray[material.materialIndex].created = Date.now();

		this.setState({
			materialComposition: materialArray
		});
	}

	handleSubmit(e) {
		const { user } = this.props;
		e.preventDefault();
		let name = this.state.name.trim();
		let unit = this.state.unit.trim();
		if (!unit && !name && this.state.materialComposition.length == 0) {
			return;
		}
		this.handleMaterialSubmit({
			name: name,
			unit: unit,
			materialComposition: this.state.materialComposition,
			User_id:user
		});
		this.setState({
			name: '',
			unit: '',
			materialComposition: [],
			constructionParts: 0,
			constructionCreation: false
		});
	}

	handleMaterialSubmit(material) {
		var materials = this.props.materials;
		// Optimistically set an id on the new comment. It will be replaced by an
		// id generated by the server. In a production application you would likely
		// not use Date.now() for this and would have a more robust system in place.
		material.id = Date.now();
		var newMaterials = materials.concat([material]);
		$.ajax({
			url: '/api/materials',
			dataType: 'json',
			type: 'POST',
			data: material,
			success: function (data) {

			}.bind(this),
			error: function (xhr, status, err) {

				console.error(this.props.url, status, err.toString());
			}.bind(this)
		});
	}

	render() {
		let subMaterials = [];
		const {unit, constructionParts, constructionCreation, name, materialComposition} = this.state
		for (var i = 0; i < this.state.constructionParts; i++) {
			subMaterials.push(
				<MaterialSelection
					key={ i }
					materialIndex={i}
					data={ this.props.materials }
					onMaterialChange={ material => this.handleMaterialChange(material) }
					materialCreation={ constructionCreation }/>
			)
		}
		const constructionSpecified = ( constructionCreation == 'standard' ||
		constructionCreation == 'prefab' );
		return (
			<form className="material-form" onSubmit={ event => this.handleSubmit(event)}>
				{ (constructionCreation /*&& !constructionSpecified*/) && <div>
					<button onClick={ e => this.createConstructionPartClicked(e, 'standard') }>Skapa material</button>
					<button onClick={ e => this.createConstructionPartClicked(e, 'prefab') }>Skapa byggdel</button>
				</div>}
				{
					constructionSpecified &&
					<div>
						{ constructionParts == 0 && <p style={{color: 'red'}}>TODO: Endast för admin (läs robin)</p> }
						<input
							type="text"
							placeholder="Produktens namn"
							value={ name }
							name="name"
							onChange={ event => this.handleNameUnitChange(event) }/>
						<input
							type="text"
							placeholder="Produktens enhet"
							value={ unit }
							name="unit"
							onChange={ event => this.handleNameUnitChange(event) }/>
					</div>
				}
				{ constructionParts > 0 &&
				<div>
					{ constructionSpecified && <h3>Bestående av:</h3> }
					{ subMaterials }
					{ name != 'byggnad01' && <div>
						<button onClick={ event => this.addConstructionPart(event) }>Lägg till material</button>
						{ constructionParts > 0 &&
						<button onClick={ event => this.removeConstructionPart(event) }>Ta bort material</button>}
					</div>}
				</div>
				}
				<br/>
				{ (unit || name) /*|| materialComposition.length != 0*/ && <input type="submit" value="Spara"/>}
				{/*<button onClick={ this.createConstructionPartClicked }>Skapa nytt Material</button>*/}
			</form>
		);
	}
}

export default connect(
	(state) => ( {
		user: state.user
	})
)(CSSModules(ConstructionForm, styles))