import $ from 'jquery';
import React from 'react';
import CSSModules from 'react-css-modules';

import styles from './ConstructionForm.less';
import MaterialSelection from './MaterialSelection.jsx';

class ConstructionForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      name: this.props.constructionName ? this.props.constructionName : '',
      unit: '',
      materialComposition: [],
      constructionParts: this.props.constructionParts ? this.props.constructionParts : 0,
      constructionCreation: this.props.constructionCreation ? this.props.constructionCreation : false
    };
    this.handleNameChange = this.handleNameChange.bind(this);
    this.handleUnitChange = this.handleUnitChange.bind(this);
    this.createConstructionPart = this.createConstructionPart.bind(this);
    this.createConstructionPartClicked = this.createConstructionPartClicked.bind(this);
    this.addConstructionPart = this.addConstructionPart.bind(this);
    this.removeConstructionPart = this.removeConstructionPart.bind(this);
    this.handleMaterialChange = this.handleMaterialChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleNameChange(e) {
    this.setState({
      name: e.target.value
    });
  }

  handleUnitChange(e) {
    this.setState({
      unit: e.target.value
    });
  }

  createConstructionPartClicked(e){
    e.preventDefault();
    this.createConstructionPart();
  }

  createConstructionPart(){
    this.setState({
      name: '',
      unit: '',
      materialComposition: [],
      constructionParts: 0,
      constructionCreation: true
    });
  }

  addConstructionPart(e){
    e.preventDefault();
    this.setState({
      constructionParts: this.state.constructionParts + 1
    });
  }

  removeConstructionPart(e){
    e.preventDefault();
    this.setState({
      constructionParts: this.state.constructionParts - 1
    });
    //FIXME: This also needs to go through the state and remove the unwanted material
  }

  handleMaterialChange(material) {
    if( material.material == 'createNew'){
      this.createConstructionPart();
      return;
    }
    let materialArray = this.state.materialComposition;
    let indexNum = 0;
    let arrIndex = {};
    this.state.materialComposition.map((constructionPart)=>{
      arrIndex[constructionPart.material]=indexNum++;
    });
    let index = arrIndex[material.material];
    if(index === undefined) {
        index = materialArray.length;
    }
    materialArray[index] = material;

    this.setState({
      materialComposition: materialArray
    });
  }

  handleSubmit(e) {
    e.preventDefault();
    let name = this.state.name.trim();
    let unit = this.state.unit.trim();
    if (!unit && !name && this.state.materialComposition.length == 0) {
      return;
    }
    this.handleMaterialSubmit({
      name: name,
      unit: unit,
      materialComposition: this.state.materialComposition
    });
    this.setState({
      name: '',
      unit: '',
      materialComposition: [],
      constructionParts: 0,
      constructionCreation: false
    });
  }

  handleMaterialSubmit(material) {
    var materials = this.props.materials;
    // Optimistically set an id on the new comment. It will be replaced by an
    // id generated by the server. In a production application you would likely
    // not use Date.now() for this and would have a more robust system in place.
    material.id = Date.now();
    var newMaterials = materials.concat([material]);
    $.ajax({
      url: '/api/materials',
      dataType: 'json',
      type: 'POST',
      data: material,
      success: function(data) {
        
      }.bind(this),
      error: function(xhr, status, err) {
        
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  }

  render() {
    let subMaterials = [];
    const { unit, constructionParts, constructionCreation, name, materialComposition } = this.state
    for (var i = 0; i < this.state.constructionParts; i++) {
        subMaterials.push(<MaterialSelection key={i} data={this.props.materials} onMaterialChange={this.handleMaterialChange}/>)
    }
    return (
      <form className="material-form" onSubmit={this.handleSubmit}>
        
        { constructionCreation ?
          <div>
            <h1>Skapa nytt material, prefabelement eller komplex-bygg-del:</h1>
            <input
              type="text"
              placeholder="Konstruktionens namn"
              value={ name }
              onChange={this.handleNameChange}/>
            <input
              type="text"
              placeholder="Konstruktionens Enhet"
              value={ unit }
              onChange={this.handleUnitChange}/>
          </div>
        :
          <div>
            <h1 styleName="headline">Rapportera använt material</h1>
          </div>
        }
        { constructionParts > 0 ? 
          <div>
            <h3>Bestående av:</h3>
            { subMaterials }
            <button onClick={ this.addConstructionPart }>Lägg till material</button>
            { constructionParts > 0 && <button onClick={this.removeConstructionPart}>Ta bort material</button>}
          </div>
          :
          <button onClick={ this.addConstructionPart }>Skapa prefab element</button>
        }
        <br/>
        { (unit || name) /*|| materialComposition.length != 0*/ && <input type="submit" value="Spara" />}
        {/*<button onClick={ this.createConstructionPartClicked }>Skapa nytt Material</button>*/}
      </form>
    );
  }
};

export default CSSModules(ConstructionForm, styles)